### ISSUE TITLE
Wind Direction in N,NNE,NE,ENE,E and so on

### ISSUE THREAD

**Issue by beyondunreal79** [tlskinneriv/awnet_local#35]
Could there be a way to give the option to see the current wind direction in cardinal direction or degrees? 

![Capture2](https://github.com/tlskinneriv/awnet_local/assets/45919008/b1183ea7-614c-4217-b226-31d63d9474b5)

**Comment by tlskinneriv** [comment]
Yep, I can definitely add that as another calculated sensor similar to the Solar Radiation in lux. Will get this in the next release.

**Comment by tlskinneriv** [comment]
Also, if you want a quick config for a template sensor for this:

```yaml
sensor:
  - platform: template
    sensors:
      home_wind_dir_cardinal:
        value_template: >
          {% set direction = ['N','NNE','NE','ENE','E','ESE','SE','SSE','S','SSW','SW','WSW','W','WNW','NW','NNW','N'] %}
          {% set degree = states('<your_winddir_entity_id>')|float(default=0) %}
          {{ direction[((degree+11.25)/22.5)|int(default=0)] }}
```
